# Generated by Django 5.2.13 on 2026-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_created_at_remove_sale_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_sack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
