# Generated by Django 5.2.13 on 2026-04-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
