# Generated by Django 5.2.13 on 2026-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_price_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_sack',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
